import Head from 'next/head'
import ContentDashboard from './ContentDashboard'
import SlideBar from './SlideBar'


const Layout = ({data}) => {
  return (
    <div className='containerMain'>
      <Head>
        <title>Home </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container'>

        <SlideBar name={'Jeremy Robson'} />

        <ContentDashboard data={data}/>
        
      </div>
      <style jsx>{`

        .containerMain{
          background:var(--Very-dark-blue);
          display: flex;
          justify-content: center;
          align-items: center;
          height: 100vh;
        }

        .container {
          display: grid;
          grid-template-columns: .9fr 3fr;
          justify-content: center;
          grid-gap: 20px;
          width: 820px;
          height: 380px;
        }

        @media (max-width:800px ){
          .container{
            width:350px;
            height:90%;
            grid-template-columns: 1fr;
            grid-template-rows: .2fr 3fr;
          }

        }

        @media (max-width:500px ){
          .container{
            width:300px;
            height:90%;
            grid-template-columns: 1fr;
            grid-template-rows: .2fr 3fr;
          }

        }
          `}</style>
    </div>

  )
}

export default Layout